json-merge needs to merge more than two spec files see if we can better name temp mountpoints for easier cleanup

diff --git a/bin/reflash b/bin/reflash
--- a/bin/reflash
+++ b/bin/reflash
@@ -491,17 +491,20 @@ identify_source()
 load_build_spec()
 {
     MERGED_SPEC=
-
-    if [[ -f "${ROOT}/build.spec" && -f "${ROOT}/build.spec.local" ]]; then
-        MERGED_SPEC=$(${ROOT}/bin/json-merge ${ROOT}/build.spec \
-        ${ROOT}/build.spec.local)
-    elif [[ -f "${ROOT}/build.spec" ]]; then
-        MERGED_SPEC=$(cat ${ROOT}/build.spec)
-    elif [[ -f "${ROOT}/build.spec.local" ]]; then
-        MERGED_SPEC=$(cat ${ROOT}/build.spec.local)
+    SPEC_SOURCES=""
+    if [[ -f "${ROOT}/build.spec" ]]; then
+        SPEC_SOURCES="$SPEC_SOURCES ${ROOT}/build.spec"
+    fi
+    if [[ -f "${ROOT}/build.spec.local" ]]; then
+        SPEC_SOURCES="$SPEC_SOURCES ${ROOT}/build.spec.local"
+    fi
+    if [[ -f "${ROOT}/build.spec.branches" ]]; then
+        SPEC_SOURCES="$SPEC_SOURCES ${ROOT}/build.spec.branches"
     fi
 
-    [[ -n ${MERGED_SPEC} ]] || fatal "Unable to load build.spec[.local]"
+    MERGED_SPEC=$(${ROOT}/bin/json-merge ${SPEC_SOURCES})
+
+    [[ -n ${MERGED_SPEC} ]] || fatal "Unable to load build.spec[.local|.branches]"
 }
 
 mget_stdout()
